# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EL PARIAN
email: elparianeventos@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ¡El espacio perfecto para tu boda! Disfruta de ese día acompañado de la naturaleza y tus invitados.
  Contamos con opción de hospedaje, salón de belleza y spa para que tu familia y tu se relajen los días previos al gran día.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
collections_dir: collections
collections:
  galleries:
    output: true
    permalink: /galleries/:path/
  featurettes:

contact: {
  email: elparianeventos@gmail.com,
  instagram: {
    username: elparianeventos,
    text: Instagram
  },
  facebook: {
    username: El-Parian-843581412474666,
    text: Facebook
  }
}

permalink: pretty

# Build settings
markdown: kramdown
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   - .idea/
